import React from "react";
import { AppRegistry } from "react-native";

// this file is generated by react-bundle-aggregator


  import arbitrary-module-name from "red-app";

  import GreenApp from "green-app";

  import ModalApp from "modal-app";



  AppRegistry.registerComponent("arbitrary-module-name",() => arbitrary-module-name);

  AppRegistry.registerComponent("GreenApp",() => GreenApp);

  AppRegistry.registerComponent("ModalApp",() => ModalApp);


