import React from "react";
import { AppRegistry } from "react-native";

// this file is generated by react-bundle-aggregator


  import RedApp from "red-app";

  import GreenApp from "green-app";

  import ModalApp from "modal-app";



  AppRegistry.registerComponent("RedApp",() => RedApp);

  AppRegistry.registerComponent("GreenApp",() => GreenApp);

  AppRegistry.registerComponent("ModalApp",() => ModalApp);


