import React from "react";
import { AppRegistry } from "react-native";
import APSportFixtures from "@applicaster/APSportFixtures-RN";
import APSportsStandings from "@applicaster/APSportStandings-RN";
import APSportTopScorers from "@applicaster/APSportTopScorers-RN";

// this file is generated by react-bundle-aggregator

AppRegistry.registerComponent(
  "SportFixtures-fullscreen",
  () => APSportFixtures
);

AppRegistry.registerComponent("standings", () => APSportsStandings);

AppRegistry.registerComponent("top_player", () => APSportTopScorers);
